table DimArea
	lineageTag: 30dc4c40-5fa6-4e73-843c-602cfa1847ad

	column AreaID
		dataType: string
		lineageTag: 7a087e82-570a-4e8b-9478-576abe217a68
		summarizeBy: none
		sourceColumn: AreaID

		annotation SummarizationSetBy = Automatic

	column AreaName
		dataType: string
		lineageTag: 27732dfc-5dba-4217-94ff-c7450dcf0201
		summarizeBy: none
		sourceColumn: AreaName

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: a0dc50a9-6e41-4eff-8b79-13d9bc0d58dd
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	column Zone
		dataType: string
		lineageTag: 69889e15-c87b-4e5b-98ef-e904ac775e94
		summarizeBy: none
		sourceColumn: Zone

		annotation SummarizationSetBy = Automatic

	column AreaType
		dataType: string
		lineageTag: 43e5996e-7054-4033-9b4d-9234974b049a
		summarizeBy: none
		sourceColumn: AreaType

		annotation SummarizationSetBy = Automatic

	partition DimArea = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Abdelghani.Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data"),
				    #"C:\Users\Abdelghani Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\_DimArea csv" = Source{[#"Folder Path"="C:\Users\Abdelghani.Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\",Name="DimArea.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\Abdelghani Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\_DimArea csv",[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Imported CSV",{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"AreaID", type text}, {"AreaName", type text}, {"Level", type text}, {"Zone", type text}, {"AreaType", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

