table FactRoster
	lineageTag: 1e710ab6-3514-4bc2-acd7-0619e2b98e56

	column RosterRecordID
		dataType: string
		lineageTag: 3fda18d9-d095-49f5-8a14-5d83b8562ae7
		summarizeBy: none
		sourceColumn: RosterRecordID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 90d27693-932d-4c37-9a62-08fd5c5e3190
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column ShiftKey
		dataType: string
		lineageTag: 4e82b5b7-50d3-4603-ad82-52dd67e25940
		summarizeBy: none
		sourceColumn: ShiftKey

		annotation SummarizationSetBy = Automatic

	column UnitCode
		dataType: string
		lineageTag: f0adb88b-9e2a-4cc5-bcbc-1277b88a7e89
		summarizeBy: none
		sourceColumn: UnitCode

		annotation SummarizationSetBy = Automatic

	column CrewName
		dataType: string
		lineageTag: 75017f14-16ed-4e99-9527-c419840bf394
		summarizeBy: none
		sourceColumn: CrewName

		annotation SummarizationSetBy = Automatic

	column OperatorAssigned
		dataType: int64
		formatString: 0
		lineageTag: af25ef2c-8b40-42c1-af19-5811026ff3e8
		summarizeBy: sum
		sourceColumn: OperatorAssigned

		annotation SummarizationSetBy = Automatic

	column OperatorSkillIndex
		dataType: double
		lineageTag: c3f562b8-36f5-4437-ac48-99f614d859c6
		summarizeBy: sum
		sourceColumn: OperatorSkillIndex

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PlannedAreaID
		dataType: string
		lineageTag: bf3ff92a-bed0-43f3-a5b0-c351bd0e8fa6
		summarizeBy: none
		sourceColumn: PlannedAreaID

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: 758adb50-340c-4d0b-83a5-d4edc216fdd2
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	partition FactRoster = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\Abdelghani.Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data"),
				    #"C:\Users\Abdelghani Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\_FactRoster csv" = Source{[#"Folder Path"="C:\Users\Abdelghani.Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\",Name="FactRoster.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(#"C:\Users\Abdelghani Bouaddi\Downloads\Northstar_GMG_PowerBI_Portfolio_Pack\Northstar_GMG_PowerBI_Portfolio_Pack\data\_FactRoster csv",[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"RosterRecordID", type text}, {"DateKey", Int64.Type}, {"ShiftKey", type text}, {"UnitCode", type text}, {"CrewName", type text}, {"OperatorAssigned", Int64.Type}, {"OperatorSkillIndex", type number}, {"PlannedAreaID", type text}, {"SourceSystem", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

